/* ============================================================================
   lib/semantica · Clasificación semántica del objeto contractual
   ----------------------------------------------------------------------------
   Regex heredados (probados en producción) del index.html histórico, extraídos
   programáticamente para evitar errores de transcripción.
   - BLACKLIST_OBJETO: objetos que ningún RUP de Helder/Génesis cubre (caninos,
     PAE, dotación, seguros, software, vigilancia armada…). Si matchea, FUERA.
   - WHITELIST_OBRA: vocabulario inequívoco de obra/ingeniería civil. Se exige
     cuando la licitación NO declara código UNSPSC (mapeo textual tolerante).
   ========================================================================== */
"use strict";

const BLACKLIST_OBJETO = /\b(canin[oa]s?|perr[oa]s?|semovientes?|equin[oa]s?|bovin[oa]s?|porcin[oa]s?|aves\s+de\s+corral|ganado|adiestramiento|alimentaci[oó]n\s+(?:escolar|pae|adulto|infantil|complement)|aliment(?:os|aria|ario)\s+(?:escolar|pae|nutric)|paquetes?\s+alimentari|refrigerios?|v[ií]veres|mercad(?:o|os)\s+(?:campesin|familiar)|almuerz(?:o|os)|desayun(?:o|os)|loncher|vestuario|uniformes?|dotaci[oó]n\s+(?:de\s+)?(?:personal|empleados|escolar|trabajadores|polici|militar)|calzado|prendas\s+(?:de\s+vestir|escolar)|medicament(?:o|os|aria)|f[aá]rmacos?|insumos?\s+m[eé]dic(?:o|os|al)|insumos?\s+hospital|dispositivos?\s+m[eé]dic|odontol[oó]gic|farmac[eé]utic|papeler[ií]a|[uú]tiles\s+de\s+oficina|t[oó]ner|impresi[oó]n\s+(?:de\s+formul|de\s+document)|combustible|gasolina|acpm\b|lubricantes|aceite\s+de\s+motor|adquisici[oó]n\s+de\s+veh[ií]culos|compra\s+de\s+veh[ií]culos|motocicletas?|cuatrimoto|automotor(?:es)?|busetas?|camion(?:es|eta)|armament|munici[oó]n(?:es)?|dotaci[oó]n\s+polici|chaleco\s+antibalas|software|licenci(?:a|as)\s+(?:inform[aá]tic|de\s+software|microsoft|adobe|office|antiviru)|ofim[aá]tica|hosting|dominio\s+web|capacitaci[oó]n|congres(?:o|os)|seminari(?:o|os)|hospedaje|alojamiento|tiquetes?\s+a[eé]reos?|transporte\s+(?:de\s+)?personal|transporte\s+escolar|fumigaci[oó]n|control\s+(?:de\s+)?(?:vectores|plagas|roedores)|aseo\s+(?:y\s+)?(?:cafeter[ií]a|general|integral|institucion)|vigilancia\s+(?:armada|privada|y\s+seguridad)|seguridad\s+privada|seguros?\s+(?:de\s+|generales|todo\s+riesgo|automotor|vida|salud)|p[oó]liza|intermediaci[oó]n\s+de\s+seguros|corretaje|telefon[ií]a|conectividad|plan\s+de\s+datos|publicidad|impresos\s+(?:y|institucion)|pendones?|plotter|jur[ií]dic(?:o|os|a|as)\s+(?:asesor|representac|defensa)|defensa\s+judicial|representaci[oó]n\s+judicial|auditor[ií]a\s+(?:contable|financiera|forense|de\s+cumplimiento|interna|de\s+gesti)|libros|biblio(?:teca|gr[aá]fico)|juguetes?|navide[ñn](?:o|a|os|as)|premios?\s+(?:y\s+est[ií]mul|escolar|deportiv)|bonos?\s+(?:navide|nutric|alimentari|escolar)|becas?|fertilizantes?|abonos?\s+(?:org[aá]nicos|qu[ií]micos)|insumos?\s+agr[ií]cola|agropecuari|fungicidas?|herbicidas?|plaguicidas?|kits?\s+(?:escolar|estudiantil|alimentari|nutric|hi?gi[eé]nic|deportiv|biosanitar)|elementos?\s+de\s+protecci[oó]n\s+(?:personal|biosanitar)|epp\b|interpretaci[oó]n\s+de\s+lenguaje|traducci[oó]n)/i;

const WHITELIST_OBRA = /\b(construcci[oó]n|construir|obra\s+(?:p[uú]blic|civil|de)|obras\s+(?:p[uú]blic|civil|de|complementari)|mejoramient[o]?\s+(?:de\s+(?:la\s+|el\s+|los\s+|las\s+)?)?(?:v[ií]a|infraestruc|sede|edifici|cancha|coleg|escuela|hospital|parque|red|acueduc|alcantarill|placa)|adecuaci[oó]n\s+(?:de\s+(?:la\s+|el\s+|los\s+|las\s+)?)?(?:sede|edifici|coleg|escuela|hospital|parque|cancha|infraestruc|v[ií]a|red|salon|sal[oó]n|aula|biblio|laborator|comedor|coliseo|estadio|cubiert)|remodelaci[oó]n|mantenimiento\s+(?:de\s+(?:la\s+|el\s+|los\s+|las\s+)?)?(?:v[ií]a|infraestruc|edifici|red(?:es)?|alcantarill|acueduc|puente|p[uú]blic|escuela|coleg|hospital|sede|parque|cancha|estadi|polid[eé]port|cubiert)|ampliaci[oó]n\s+(?:de\s+(?:la\s+|el\s+|los\s+|las\s+)?)?(?:v[ií]a|red|edifici|acueduc|alcantarill|cobertur)|optimizaci[oó]n\s+(?:de\s+(?:la\s+|el\s+|los\s+|las\s+)?)?(?:red|sistema|acueduc|alcantarill|infraestruc)|rehabilitaci[oó]n\s+(?:de\s+(?:la\s+|el\s+|los\s+|las\s+)?)?(?:v[ií]a|red|acueduc|alcantarill|edifici|cubierta|sede|coleg)|pavimentaci[oó]n|pavimento|asfalto|asf[aá]ltic|repavimentaci[oó]n|parcheo|v[ií]a\s+(?:terciari|secundari|urban|rural)|v[ií]as\s+(?:terciari|secundari|urban|rural)|carretera|carreteable|and[eé]n|aceras?|sardineles?|placa\s*huella|placahuella|puente\s+(?:vehicular|peaton|colgant|en\s+concret)|pontones?|box\s*culvert|alcantarill|acueducto|ptar\b|ptap\b|red(?:es)?\s+(?:de\s+)?(?:acueduct|alcantarill|el[eé]ctric|hidr[aá]ulic|sanitari|gas|distribuci|m[eé]dia\s+tensi|baja\s+tensi)|edificaci[oó]n|edificio\s+(?:p[uú]blic|institucion|administra|educativ)|coleg(?:io|ial)|polid[eé]port|urbanismo|espacio\s+p[uú]blico|drenaje|gavion(?:es)?|muro\s+de\s+contenci[oó]n|cuneta|interventor[ií]a\s+(?:t[eé]cnica|de\s+obra|para\s+la\s+obra|al\s+contrato\s+de\s+obra|administrativa\s+y\s+t[eé]cnica)|consultor[ií]a\s+(?:t[eé]cnica|de\s+obra|para\s+(?:el\s+dise|los\s+estudio|la\s+construc))|estudios?\s+y\s+dise[ñn]os?|dise[ñn]o(?:s)?\s+(?:t[eé]cnic|estructura|hidr[aá]ulic|el[eé]ctric|arquitect|de\s+obra|para\s+(?:obra|construc))|demolici[oó]n|reforzamiento\s+(?:estructur|s[ií]smic)|canalizaci[oó]n|cubierta\s+(?:met[aá]lic|liviana|en\s+teja)|electrificaci[oó]n\s+(?:rural|de\s+)?(?:red|vereda|barrio)|alumbrado\s+p[uú]blic|iluminaci[oó]n\s+(?:v[ií]al|p[uú]blic|parque|cancha)|se[ñn]alizaci[oó]n\s+(?:v[ií]al|horizontal|vertical)|tanque\s+(?:de\s+almacen|elevad|enterr|el[eé]vado)|pozo\s+(?:profun|s[eé]ptic|subterr)|infraestructura\s+(?:v[ií]al|educativ|deportiv|de\s+salud|sanitari|el[eé]ctric|hidr[aá]ulic|p[uú]blic)|sistema\s+(?:de\s+)?(?:acueduc|alcantarill|tratamient\s+de\s+agua))/i;

module.exports = { BLACKLIST_OBJETO, WHITELIST_OBRA };
